export {default as HomeView}from './HomeView.vue'
export {default as AboutView}from './AboutView.vue'
export {default as SkillView}from './SkillView.vue'
export {default as WorksView}from './WorksView.vue'
export {default as ContactView}from './ContactView.vue'