export {default as Navbar} from './Navbar.vue'
export {default as About} from './About.vue'
export {default as Home} from './Home.vue'
export {default as Skill}from './Skill.vue'
export {default as Works}from './Works.vue'
export {default as Contact}from './Contact.vue'